"""add_needs_return_to_visits

Revision ID: 4b782110b6d1
Revises: 99aa61d63ed4
Create Date: 2026-08-20 14:44:42.603996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b782110b6d1'
down_revision: Union[str, Sequence[str], None] = '99aa61d63ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('needs_return', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'needs_return')
    # ### end Alembic commands ###
