"""add_follow_up_date_to_visits_and_outreach

Revision ID: 99aa61d63ed4
Revises: 9cda6424c61a
Create Date: 2026-08-20 14:40:07.977535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99aa61d63ed4'
down_revision: Union[str, Sequence[str], None] = '9cda6424c61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach_log', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('visits', sa.Column('follow_up_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'follow_up_date')
    op.drop_column('outreach_log', 'follow_up_date')
    # ### end Alembic commands ###
